### ISSUE TITLE
Annotator name cleared after every app update

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#127] opened 2019-07-12 16:30 UTC
Hello,
it seems that the annotator name (Setting, General, Others) always clears after updating the app.

**Comment by ryouchinsa** [comment] 2019-07-15 04:03
Thanks for writing the issue.

When we close RectLabel without opening the settings dialog, this happens.

We could reproduce the same situation by the process below.
Launch RectLabel => Import settings file => close RectLabel

This problem was fixed by the latest version 2.87.

For the latest update, we checked the annotator is cleared when updating the app.
It looks that before updating RectLabel, RectLabel is launched in the background to check there is an update notification.

So that the annotator name is cleared not when you update but when you have an update notification.
This is because the previous version is launched in the background.

The latest version is 2.87.
We think the next update for the version 2.88, this problem would be fixed.

**Closed by ryouchinsa** 2019-07-15 04:03 UTC
